[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
