[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
RobotZoo = "74be38bb-dcc2-4b9e-baf3-d6373cd95f10"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
