[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
MuJoCo = "93189219-7048-461c-94ec-443a161ed927"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
RobotZoo = "74be38bb-dcc2-4b9e-baf3-d6373cd95f10"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
